[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[lib]
name = "tools"
path = "src/lib.rs"

[dependencies]
mysql = "25.0"
chrono = "0.4"
csv = "1.4.0"
serde = { version = "1.0", features = ["derive"] }